name: Build Extension

on:
  workflow_dispatch: # Permette di avviarlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del codice
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Installazione dipendenze
      run: npm install

    - name: Installazione vsce (strumento di packaging)
      run: npm install -g @vscode/vsce

    - name: Creazione pacchetto .vsix
      run: vsce package

    - name: Caricamento artefatto (il file .vsix)
      uses: actions/upload-artifact@v4
      with:
        name: category-finder-extension
        path: "*.vsix"